# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0-rc2


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
from sklearn import datasets
iris = datasets.load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [5]:
X = iris.data
Y = iris.target
print (X)
print (Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=1, stratify = Y)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
Y_train = tf.keras.utils.to_categorical(Y_train, num_classes=3)
Y_test = tf.keras.utils.to_categorical(Y_test, num_classes=3)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
#Add Dense Layer  applying softmax
model.add(tf.keras.layers.Dense(3, activation='softmax',input_shape=(4,)))



## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:


#Compile the model
model.compile(optimizer='sgd', loss='categorical_crossentropy', 
              metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [15]:
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization (BatchNo multiple                  16        
_________________________________________________________________
dense (Dense)                multiple                  15        
Total params: 31
Trainable params: 23
Non-trainable params: 8
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [14]:
model.fit(X_train, Y_train,epochs=100)

Train on 112 samples
Epoch 1/100
112/112 [==============================] - 1s 5ms/sample - loss: 1.2689 - accuracy: 0.3125
Epoch 2/100
112/112 [==============================] - 0s 118us/sample - loss: 1.1912 - accuracy: 0.3393
Epoch 3/100
112/112 [==============================] - 0s 134us/sample - loss: 1.1400 - accuracy: 0.3571
Epoch 4/100
112/112 [==============================] - 0s 103us/sample - loss: 1.0725 - accuracy: 0.3571
Epoch 5/100
112/112 [==============================] - 0s 118us/sample - loss: 0.9937 - accuracy: 0.4375
Epoch 6/100
112/112 [==============================] - 0s 137us/sample - loss: 0.9629 - accuracy: 0.5446
Epoch 7/100
112/112 [==============================] - 0s 114us/sample - loss: 0.9074 - accuracy: 0.6518
Epoch 8/100
112/112 [==============================] - 0s 151us/sample - loss: 0.8808 - accuracy: 0.6964
Epoch 9/100
112/112 [==============================] - 0s 124us/sample - loss: 0.8242 - accuracy: 0.7589
Epoch 10/100
112/112 [==============

## Question 10

### Make predictions
- Predict labels on one row

In [16]:
import numpy as np
input_data = np.expand_dims(X_test[0], axis=0)
print(input_data.shape)
pred = model.predict(input_data)
pred


(1, 4)


array([[0.01030674, 0.4095837 , 0.58010954]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [17]:
np.argmax(Y_test[0])

2



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [52]:
import tensorflow as tf
print(tf.__version__)

2.0.0-rc2


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [54]:
import pandas as pd
df = pd.read_csv("prices.csv")
df.head(5)

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [55]:
df = df.drop(columns = ['date','symbol'],axis = 1)
df.head(5)

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [56]:
df_fist1000 = df.iloc[0:1000,]
df_fist1000.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
X = df_fist1000.drop('volume',axis = 1)
Y = df_fist1000['volume']
Y = Y / 1000000


## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
X_np = X.to_numpy()
X_np = X_np.astype('float32')
Y_np = Y.to_numpy()
Y_np = Y_np.astype('float32')


In [59]:
print(X_np.dtype)
print(Y_np.dtype)
X_np

float32
float32


array([[123.43, 125.84, 122.31, 126.25],
       [125.24, 119.98, 119.94, 125.54],
       [116.38, 114.95, 114.93, 119.74],
       ...,
       [ 28.32,  28.77,  28.01,  28.81],
       [ 44.  ,  44.8 ,  43.75,  44.81],
       [ 36.08,  37.14,  36.01,  37.23]], dtype=float32)

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [60]:
X_norm = tf.math.l2_normalize(X_np)
X_norm


<tf.Tensor: id=6737, shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
#We are initializing weights and Bias with Zero
w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
def prediction(x, w, b):
    
    xw_matmul = tf.matmul(x, w)
    y = tf.add(xw_matmul, b)
    
    return y

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
def loss(y_actual, y_predicted):
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    
    return avg
  
  


## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [65]:


#Train for 100 Steps
for i in range(100):
    
    w, b = train(X_norm, Y_np, w, b, learning_rate=0.01)
    print('Current Loss on iteration', i, 
          loss(Y_np, prediction(X_norm, w, b)).numpy())

Current Loss on iteration 0 236.16759
Current Loss on iteration 1 235.09299
Current Loss on iteration 2 234.06102
Current Loss on iteration 3 233.06998
Current Loss on iteration 4 232.11781
Current Loss on iteration 5 231.20381
Current Loss on iteration 6 230.32585
Current Loss on iteration 7 229.48265
Current Loss on iteration 8 228.67297
Current Loss on iteration 9 227.89539
Current Loss on iteration 10 227.14832
Current Loss on iteration 11 226.43114
Current Loss on iteration 12 225.74234
Current Loss on iteration 13 225.0808
Current Loss on iteration 14 224.44553
Current Loss on iteration 15 223.835
Current Loss on iteration 16 223.24931
Current Loss on iteration 17 222.68655
Current Loss on iteration 18 222.14595
Current Loss on iteration 19 221.62688
Current Loss on iteration 20 221.12842
Current Loss on iteration 21 220.6498
Current Loss on iteration 22 220.18993
Current Loss on iteration 23 219.74841
Current Loss on iteration 24 219.32425
Current Loss on iteration 25 218.91705


### Observe values of Weight
- Print the updated values

In [66]:
#Check Weights and Bias
print('Weights:\n', w.numpy())


Weights:
 [[0.0547828 ]
 [0.05488191]
 [0.05422735]
 [0.05533117]]


### Observe values of Bias
- Print the updated values

In [67]:
print('Bias:\n',b.numpy())

Bias:
 [4.607657]
