### Build a DNN using Keras with `RELU` and `ADAM`

#### Load tensorflow

In [1]:
import tensorflow as tf
import numpy as np
from keras.layers import Dense, Activation, Dropout, Flatten, Reshape

Using TensorFlow backend.


#### Collect Fashion mnist data from tf.keras.datasets 

In [2]:
from keras.datasets import fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

In [3]:
x_train.shape

(60000, 28, 28)

In [4]:
print(y_train.shape)
y_train[0:100]

(60000,)


array([9, 0, 0, 3, 0, 2, 7, 2, 5, 5, 0, 9, 5, 5, 7, 9, 1, 0, 6, 4, 3, 1,
       4, 8, 4, 3, 0, 2, 4, 4, 5, 3, 6, 6, 0, 8, 5, 2, 1, 6, 6, 7, 9, 5,
       9, 2, 7, 3, 0, 3, 3, 3, 7, 2, 2, 6, 6, 8, 3, 3, 5, 0, 5, 5, 0, 2,
       0, 0, 4, 1, 3, 1, 6, 3, 1, 4, 4, 6, 1, 9, 1, 3, 5, 7, 9, 7, 1, 7,
       9, 9, 9, 3, 2, 9, 3, 6, 4, 1, 1, 8], dtype=uint8)

In [5]:
x_test.shape

(10000, 28, 28)

In [6]:
y_test[0]

9

#### Change train and test labels into one-hot vectors

In [7]:
y_train = tf.keras.utils.to_categorical(y_train,num_classes = 10)
y_test = tf.keras.utils.to_categorical(y_test,num_classes = 10)
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [8]:
x_test = x_test/255.0   # Normalising the input data
x_train = x_train/255.0

#### Build the Graph

#### Initialize model, reshape & normalize data

In [9]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

#### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [10]:
model.add(tf.keras.layers.Dense(200, activation='relu'))  # FC1

model.add(tf.keras.layers.Dense(100, activation='relu')) #FC2

model.add(tf.keras.layers.Dropout(0.25)) #dropout

### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [11]:
model.add(tf.keras.layers.Dense(10, activation='softmax')) # output layer

In [12]:
# Complie
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam',metrics =['accuracy'])

In [13]:
model.fit(x_train,y_train,epochs = 10, batch_size = 32, validation_data = (x_test,y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 11s 186us/sample - loss: 0.5079 - accuracy: 0.8174 - val_loss: 0.4067 - val_accuracy: 0.8508
Epoch 2/10
60000/60000 [==============================] - 9s 154us/sample - loss: 0.3941 - accuracy: 0.8557 - val_loss: 0.3755 - val_accuracy: 0.8623
Epoch 3/10
60000/60000 [==============================] - 9s 152us/sample - loss: 0.3570 - accuracy: 0.8687 - val_loss: 0.3696 - val_accuracy: 0.8676
Epoch 4/10
60000/60000 [==============================] - 9s 151us/sample - loss: 0.3322 - accuracy: 0.8767 - val_loss: 0.3542 - val_accuracy: 0.8699
Epoch 5/10
60000/60000 [==============================] - 9s 151us/sample - loss: 0.3086 - accuracy: 0.8848 - val_loss: 0.3466 - val_accuracy: 0.8746
Epoch 6/10
60000/60000 [==============================] - 9s 152us/sample - loss: 0.2962 - accuracy: 0.8890 - val_loss: 0.3485 - val_accuracy: 0.8761
Epoch 7/10
60000/60000 [=========================

In [19]:
#sample validation
input_data = np.expand_dims(x_test[22], axis=0)
print(input_data.shape)
pred = model.predict(input_data)
pred

(1, 28, 28)


array([[1.8699087e-13, 2.8313420e-14, 3.0988894e-12, 1.4323537e-12,
        9.2045740e-13, 3.7824407e-06, 3.4844492e-11, 9.9998450e-01,
        3.0038564e-08, 1.1720489e-05]], dtype=float32)

In [20]:
np.argmax(pred)

7

In [21]:
y_test[22]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)